version: '3.1'

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: center
    volumes:
      - ./sql:/home/sql
      - ./csv:/home/csv
      - postgres_volume:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_volume:
