version: '3.8'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - CLUSTER_COUNT=2

volumes:
  postgres_data:
